// Code generated by internal/mcp/gen from spec/mcp-tools.json; DO NOT EDIT.

package mcp

// instructions is what the assistant reads when it connects.
const instructions = `Transpareo holds a workspace's products, components and Digital
Product Passports. Start with me to learn what the credential
allows. For a new product call product_property_types before
create_product. For passports of an existing product call
dpp_requirements, then validate_dpp before create_dpp. publish_dpp
signs the passport and cannot be undone. Recalling a unit is a
status change to suspended through append_dpp_event, not a void;
void_dpp is for a unit that no longer exists. void_dpp and
supersede_dpp need the confirm argument with the stated phrase.
Anything without a tool: search_operations, then call_api. Lists
are paged; follow nextPage.`

// curated is the tool table, one entry per tool the catalogue
// declares over an operation. Every other operation of the
// registry is in viaCallAPIOnly, hidden from consumers, or a
// user-only operation; a test enforces it.
var curated = []Tool{
	{
		Name:        "append_dpp_event",
		Group:       GroupDpps,
		Operation:   "append_dpp_event",
		Kind:        kindWrite,
		Description: `Recalling a unit is an event here: a status change to suspended, so the passport goes on answering a scan with the recall.`,
	},
	{
		Name:        "bulk_create_dpps",
		Group:       GroupDpps,
		Operation:   "bulk_create_dpps",
		Kind:        kindRows,
		Description: `Rows are deduplicated by their identifiers, so resubmitting after a timeout creates nothing twice.`,
	},
	{
		Name:      "bulk_validate_dpps",
		Group:     GroupDpps,
		Operation: "validate_dpps_bulk",
		Kind:      kindRows,
	},
	{
		Name:      "create_brand",
		Group:     GroupProducts,
		Operation: "create_brand",
		Kind:      kindWrite,
	},
	{
		Name:      "create_component",
		Group:     GroupProducts,
		Operation: "create_component",
		Kind:      kindWrite,
	},
	{
		Name:      "create_dpp",
		Group:     GroupDpps,
		Operation: "create_dpp",
		Kind:      kindWrite,
	},
	{
		Name:        "create_mediafile",
		Group:       GroupProducts,
		Operation:   "create_mediafile",
		Kind:        kindWrite,
		Description: `A link goes in under url and the server reads the bytes; a small image can go in as base64 under data.`,
	},
	{
		Name:        "create_product",
		Group:       GroupProducts,
		Operation:   "create_product",
		Kind:        kindWrite,
		Description: `Call product_property_types first: a product missing a mandatory property is refused.`,
	},
	{
		Name:        "create_webhook",
		Group:       GroupWebhooks,
		Operation:   "create_webhook",
		Kind:        kindWrite,
		Description: `The answer carries the signing secret, shown only here.`,
	},
	{
		Name:      "delete_webhook",
		Group:     GroupWebhooks,
		Operation: "delete_webhook",
		Kind:      kindWrite,
		Confirm:   "delete <id>",
	},
	{
		Name:        "dpp_requirements",
		Group:       GroupDpps,
		Operation:   "get_dpp_requirements",
		Kind:        kindGet,
		Description: `The answer carries a body ready to fill for validate_dpp and create_dpp.`,
	},
	{
		Name:      "get_component",
		Group:     GroupProducts,
		Operation: "get_component",
		Kind:      kindGet,
	},
	{
		Name:      "get_dpp",
		Group:     GroupDpps,
		Operation: "get_dpp",
		Kind:      kindGet,
	},
	{
		Name:      "get_product",
		Group:     GroupProducts,
		Operation: "get_product",
		Kind:      kindGet,
	},
	{
		Name:      "list_brands",
		Group:     GroupProducts,
		Operation: "list_brands",
		Kind:      kindList,
	},
	{
		Name:      "list_components",
		Group:     GroupProducts,
		Operation: "list_components",
		Kind:      kindList,
	},
	{
		Name:      "list_dpps",
		Group:     GroupDpps,
		Operation: "list_dpps",
		Kind:      kindList,
	},
	{
		Name:      "list_mediafiles",
		Group:     GroupProducts,
		Operation: "list_mediafiles",
		Kind:      kindList,
	},
	{
		Name:      "list_products",
		Group:     GroupProducts,
		Operation: "list_products",
		Kind:      kindList,
	},
	{
		Name:      "list_webhooks",
		Group:     GroupWebhooks,
		Operation: "list_webhooks",
		Kind:      kindList,
	},
	{
		Name:        "me",
		Group:       GroupIdentity,
		Operation:   "get_me",
		Kind:        kindGet,
		Description: `Start here: what the credential allows, its scope and rate limit.`,
	},
	{
		Name:        "product_property_types",
		Group:       GroupProducts,
		Operation:   "get_new_product",
		Kind:        kindGet,
		Description: `The property types a new product can carry, with the mandatory ones flagged: the body create_product needs.`,
	},
	{
		Name:        "publish_dpp",
		Group:       GroupDpps,
		Operation:   "publish_dpp",
		Kind:        kindWrite,
		Description: `Signs a snapshot into the ten-year archive. Publishing cannot be undone.`,
	},
	{
		Name:      "publish_product",
		Group:     GroupProducts,
		Operation: "publish_product",
		Kind:      kindWrite,
	},
	{
		Name:        "regenerate_webhook_secret",
		Group:       GroupWebhooks,
		Operation:   "regenerate_webhook_secret",
		Kind:        kindWrite,
		Confirm:     "regenerate <id>",
		Description: `The old secret stops working at once; the answer carries the new one, shown only here.`,
	},
	{
		Name:      "reissue_dpp",
		Group:     GroupDpps,
		Operation: "reissue_dpp",
		Kind:      kindWrite,
	},
	{
		Name:      "supersede_dpp",
		Group:     GroupDpps,
		Operation: "supersede_dpp",
		Kind:      kindWrite,
		Confirm:   "supersede <id>",
	},
	{
		Name:      "test_webhook",
		Group:     GroupWebhooks,
		Operation: "test_webhook",
		Kind:      kindWrite,
	},
	{
		Name:      "unpublish_product",
		Group:     GroupProducts,
		Operation: "unpublish_product",
		Kind:      kindWrite,
	},
	{
		Name:      "update_component",
		Group:     GroupProducts,
		Operation: "update_component",
		Kind:      kindWrite,
	},
	{
		Name:      "update_dpp",
		Group:     GroupDpps,
		Operation: "update_dpp",
		Kind:      kindWrite,
	},
	{
		Name:      "update_dynamic_data",
		Group:     GroupDpps,
		Operation: "update_dpp_dynamic_data",
		Kind:      kindWrite,
	},
	{
		Name:      "update_product",
		Group:     GroupProducts,
		Operation: "update_product",
		Kind:      kindWrite,
	},
	{
		Name:        "update_product_mediafiles",
		Group:       GroupProducts,
		Operation:   "update_product_mediafiles",
		Kind:        kindWrite,
		Description: `Replaces a product's images with the ones named, in the order given.`,
	},
	{
		Name:        "validate_dpp",
		Group:       GroupDpps,
		Operation:   "validate_dpp",
		Kind:        kindWrite,
		Description: `Runs the checks a publish runs, writes nothing. Call it before create_dpp.`,
	},
	{
		Name:        "void_dpp",
		Group:       GroupDpps,
		Operation:   "void_dpp",
		Kind:        kindWrite,
		Confirm:     "void <id>",
		Description: `For a unit that no longer exists. To recall one that is still in the field, use append_dpp_event instead.`,
	},
}
